version: '3'

services: 
  #supplements-service:
  #  build: ./qrebelsupplements
  #  ports: 
  #   - 30001:8081
  qrebel-jenkins:
    build: ./qrebeljenkins
    ports:
      - 30002:8088
      - 30003:7000
      - 30004:443
      - 30005:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #depends_on: 
     # - supplements-service


networks:
  default:
    external:
      name: spring-petclinic-microservices_default
