version: '3.5'

services: 
  qrebel-jenkins:
    build: ./qrebeljenkins
    ports:
      - 30002:8088
      - 30003:7000
      - 30004:443
      - 30005:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    networks:
      - qrebel-demo-env



networks:
# https://forums.docker.com/t/set-default-network-name-for-compose/36779/2
# https://docs.docker.com/compose/compose-file/#name-1
  qrebel-demo-env:
    name: qrebel-demo-env-net
#  default:
#    external:
#      name: spring-petclinic-microservices_default

volumes:
  jenkins-data: