version: '3'

services: 
  qrebel-jenkins:
    build: ./qrebeljenkins
    ports:
      - 30002:8088
      - 30003:7000
      - 30004:443
      - 30005:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home



networks:
  default:
    external:
      name: spring-petclinic-microservices_default

volumes:
  jenkins-data: